# Generated by Django 3.0.7 on 2020-06-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cash',
            field=models.FloatField(blank=True, default=1000, null=True),
        ),
    ]
