# Generated by Django 3.0.7 on 2020-06-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200627_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refund',
            name='purchase',
        ),
        migrations.AddField(
            model_name='refund',
            name='admin_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='refund',
            name='purchase_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Purchase'),
        ),
    ]
