# Generated by Django 3.0.7 on 2020-06-29 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200628_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refund',
            old_name='purchase_id',
            new_name='purchase',
        ),
    ]
