# Generated by Django 3.0.7 on 2020-06-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200629_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='admin_confirmed',
            field=models.BooleanField(null=True),
        ),
    ]
